#! /bin/bash

echo "Running all \"if\" tests basic progs "
echo "(a diff will be done comparing exp with produced output)"
echo "all used files are in the sub dir examples/test_if, "
echo "if you want to look at them..."

echo 

echo "Test 1: Test if"
./basic_interprete examples/test_if/test_if.bas &> examples/test_if/temp
echo "Difference between produced and exp output:"
diff examples/test_if/temp examples/test_if/test_if_exp_out.txt
echo "End test 1."

echo

echo "Test 2: Test if without then"
./basic_interprete examples/test_if/test_if_withOut_then.bas &> examples/test_if/temp
echo "Difference between produced and exp output:"
diff examples/test_if/temp examples/test_if/test_if_withOut_then_exp_out.txt
echo "End test 2."

echo

rm examples/test_if/temp
 
